import { createStyles } from "@material-ui/core";

const styles = createStyles({
  root: {},
  text: {
    textAlign: "center",
    fontSize: "14px",
    color: "white",
  },
  colorless: {
    height: "30px",
    width: "120px",
    backgroundColor: "#bab7b6",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "24px",
  },
  darkness: {
    height: "30px",
    width: "120px",
    backgroundColor: "#040706",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "24px",
  },
  dragon: {
    height: "30px",
    width: "120px",
    backgroundColor: "#448b94",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "24px",
  },
  fairy: {
    height: "30px",
    width: "120px",
    backgroundColor: "#e91368",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "24px",
  },
  fighting: {
    height: "30px",
    width: "120px",
    backgroundColor: "#dd5c35",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "24px",
  },
  fire: {
    height: "30px",
    width: "120px",
    backgroundColor: "#f27d0c",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "24px",
  },
  grass: {
    height: "30px",
    width: "120px",
    backgroundColor: "#27cb4f",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "24px",
  },
  ground: {
    height: "30px",
    width: "120px",
    backgroundColor: "#a9702c",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "24px",
  },
  lightning: {
    height: "30px",
    width: "120px",
    backgroundColor: "#fbfb72",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "24px",
  },
  physic: {
    height: "30px",
    width: "120px",
    backgroundColor: "#a42a6c",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "24px",
  },
  metal: {
    height: "30px",
    width: "120px",
    backgroundColor: "#4a180b",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "24px",
  },

  water: {
    height: "30px",
    width: "120px",
    backgroundColor: "#1552e2",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "24px",
  },
});

export default styles;
